import Foundation

/// Локализация интерфейса на 16 языков (вкомпилированные строки)
enum L10n {
    // MARK: - Меню
    static var menuAutoSwitch: String { s("menu.autoSwitch") }
    static var menuCheckPermissions: String { s("menu.checkPermissions") }
    static var menuSettings: String { s("menu.settings") }
    static var menuQuit: String { s("menu.quit") }

    // MARK: - Визард разрешений
    static var wizardPermissionsResetTitle: String { s("wizard.permissionsReset.title") }
    static var wizardPermissionsResetText: String { s("wizard.permissionsReset.text") }
    static var permissionsOkTitle: String { s("wizard.permissionsOk.title") }
    static var permissionsOkText: String { s("wizard.permissionsOk.text") }
    static var wizardLaunchAtLoginTitle: String { s("wizard.launchAtLogin.title") }
    static var wizardLaunchAtLoginText: String { s("wizard.launchAtLogin.text") }
    static var wizardYes: String { s("wizard.yes") }
    static var wizardNo: String { s("wizard.no") }

    // MARK: - Настройки
    static var settingsTitle: String { s("settings.title") }
    static var settingsTabGeneral: String { s("settings.tab.general") }
    static var settingsTabAbout: String { s("settings.tab.about") }
    static var settingsAutoSwitch: String { s("settings.autoSwitch") }
    static var settingsLaunchAtLogin: String { s("settings.launchAtLogin") }
    static var settingsLayout1: String { s("settings.layout1") }
    static var settingsLayout2: String { s("settings.layout2") }
    static var settingsAutoDetect: String { s("settings.autoDetect") }
    static var settingsVersion: String { s("settings.version") }
    static var settingsHotkey: String { s("settings.hotkey") }
    static var settingsLanguage: String { s("settings.language") }
    static var settingsLanguageAuto: String { s("settings.languageAuto") }

    static var settingsPerAppLayout: String { s("settings.perAppLayout") }
    static var settingsTrigger: String { s("settings.trigger") }
    static var settingsTriggerRightOnly: String { s("settings.triggerRightOnly") }
    static var settingsTriggerDoubleTap: String { s("settings.triggerDoubleTap") }
    static var settingsTriggerHint: String { s("settings.triggerHint") }
    static var menuKeySound: String { s("menu.keySound") }
    static var menuCaretFlag: String { s("menu.caretFlag") }
    static var menuMonoIcon: String { s("menu.monoIcon") }
    static var settingsCaretFlag: String { s("settings.caretFlag") }
    static var settingsCaretFlagHint: String { s("settings.caretFlag.hint") }

    // MARK: - Language names (для выпадающего списка)

    /// Названия языков на их родном языке
    static let languageNames: [(code: String, name: String)] = [
        ("en", "English"),
        ("ru", "Русский"),
        ("uk", "Українська"),
        ("be", "Беларуская"),
        ("de", "Deutsch"),
        ("fr", "Français"),
        ("es", "Español"),
        ("pt", "Português"),
        ("pl", "Polski"),
        ("zh", "中文"),
        ("ja", "日本語"),
        ("ko", "한국어"),
        ("el", "Ελληνικά"),
        ("bg", "Български"),
        ("hy", "Հայերեն"),
        ("ka", "ქართული"),
    ]

    // MARK: - Private

    nonisolated(unsafe) private static var currentLang: String = detectLanguage()

    static let supportedLanguages = Set(["en", "ru", "de", "fr", "es", "pt", "zh", "ja", "ko", "uk", "pl", "be", "el", "bg", "hy", "ka"])

    private static func detectLanguage() -> String {
        // Проверяем принудительный язык из настроек
        let forced = UserDefaults.standard.string(forKey: "com.ruswitcher.interfaceLanguage") ?? ""
        if !forced.isEmpty && supportedLanguages.contains(forced) {
            return forced
        }
        // Авто-определение по системе
        let preferred = Locale.preferredLanguages.first ?? "en"
        let code = String(preferred.prefix(2))
        return supportedLanguages.contains(code) ? code : "en"
    }

    /// Перезагрузить язык (вызывается при смене в настройках)
    static func reloadLanguage() {
        currentLang = detectLanguage()
    }

    private static func s(_ key: String) -> String {
        strings[currentLang]?[key] ?? strings["en"]![key] ?? key
    }

    // MARK: - Все строки

    private static let strings: [String: [String: String]] = [
        // ========== ENGLISH ==========
        "en": [
            "menu.autoSwitch": "Enable RuSwitcher",
            "menu.checkPermissions": "Check Permissions…",
            "menu.settings": "Settings…",
            "menu.quit": "Quit",

            "wizard.permissionsReset.title": "Permissions Reset After Update",
            "wizard.permissionsReset.text": "macOS has reset permissions because the app was updated.\n\nRuSwitcher will remove old entries and request permissions again.\nYou just need to flip the toggles.",
            "wizard.permissionsOk.title": "All Permissions Granted",
            "wizard.permissionsOk.text": "Accessibility and Input Monitoring are enabled. RuSwitcher is working.",
            "wizard.accessibility.title": "Step 1 of 2: Accessibility",
            "wizard.accessibility.text": "RuSwitcher needs Accessibility permission.\n\nSettings will open — add RuSwitcher.\nThe app will detect it automatically.",
            "wizard.inputMonitoring.title": "Step 2 of 2: Input Monitoring",
            "wizard.inputMonitoring.text": "Now Input Monitoring permission is needed.\n\n⚠️ macOS will require an app restart after adding.\nRuSwitcher will restart automatically.",
            "wizard.openSettings": "Open Settings",
            "wizard.later": "Later",
            "wizard.launchAtLogin.title": "Launch at Login",
            "wizard.launchAtLogin.text": "Would you like RuSwitcher to start automatically when you log in?\n\nYou can change this later in Settings.",
            "wizard.yes": "Yes",
            "wizard.no": "No",

            "settings.title": "RuSwitcher — Settings",
            "settings.tab.general": "General",
            "settings.tab.about": "About",
            "settings.autoSwitch": "Enable RuSwitcher",
            "settings.trigger": "Trigger:",
            "settings.triggerRightOnly": "Right key only",
            "settings.triggerDoubleTap": "Double tap",
            "settings.triggerHint": "Tap the chosen key by itself, without other keys.",
            "menu.keySound": "Layout sound (beta)",
            "menu.caretFlag": "Flag at cursor (beta)",
            "menu.monoIcon": "Monochrome icon",
            "settings.caretFlag": "Show layout flag at the text cursor (beta)",
            "settings.caretFlag.hint": "Briefly shows the layout flag next to the text cursor after a switch. Not available in all apps.",
            "settings.launchAtLogin": "Launch at login",
            "settings.layout1": "Layout 1:",
            "settings.layout2": "Layout 2:",
            "settings.autoDetect": "Auto-detect",
            "settings.version": "Lightweight alternative to PuntoSwitcher",
            "settings.hotkey": "Tap the trigger key alone — converts the last word. Double tap — reverse.",
            "settings.language": "Interface language:",
            "settings.languageAuto": "System default",
            "settings.perAppLayout": "Remember layout per application",

        ],

        // ========== РУССКИЙ ==========
        "ru": [
            "menu.autoSwitch": "Включить RuSwitcher",
            "menu.checkPermissions": "Проверить разрешения…",
            "menu.settings": "Настройки…",
            "menu.quit": "Выход",

            "wizard.permissionsReset.title": "Разрешения сброшены после обновления",
            "wizard.permissionsReset.text": "macOS сбросил разрешения из-за обновления программы.\n\nRuSwitcher удалит старые записи и запросит разрешения заново.\nВам нужно только включить тумблеры.",
            "wizard.permissionsOk.title": "Все разрешения на месте",
            "wizard.permissionsOk.text": "«Универсальный доступ» и «Мониторинг ввода» включены. RuSwitcher работает.",
            "wizard.accessibility.title": "Шаг 1 из 2: Универсальный доступ",
            "wizard.accessibility.text": "RuSwitcher нужно разрешение Accessibility.\n\nОткроются настройки — добавьте RuSwitcher.\nПрограмма определит автоматически.",
            "wizard.inputMonitoring.title": "Шаг 2 из 2: Мониторинг ввода",
            "wizard.inputMonitoring.text": "Теперь нужно разрешение Input Monitoring.\n\n⚠️ macOS потребует перезапуск приложения.\nRuSwitcher перезапустится автоматически.",
            "wizard.openSettings": "Открыть настройки",
            "wizard.later": "Позже",
            "wizard.launchAtLogin.title": "Автозагрузка",
            "wizard.launchAtLogin.text": "Запускать RuSwitcher автоматически при входе в систему?\n\nЭто можно изменить позже в Настройках.",
            "wizard.yes": "Да",
            "wizard.no": "Нет",

            "settings.title": "RuSwitcher — Настройки",
            "settings.tab.general": "Основные",
            "settings.tab.about": "О программе",
            "settings.autoSwitch": "Включить RuSwitcher",
            "settings.trigger": "Триггер:",
            "settings.triggerRightOnly": "Только правая клавиша",
            "settings.triggerDoubleTap": "Двойной тап",
            "settings.triggerHint": "Нажимайте выбранную клавишу отдельно, без других клавиш.",
            "menu.keySound": "Звук раскладки (бета)",
            "menu.caretFlag": "Флаг у курсора (бета)",
            "menu.monoIcon": "Монохромная иконка",
            "settings.caretFlag": "Показывать флаг раскладки у курсора (бета)",
            "settings.caretFlag.hint": "После переключения ненадолго показывает флаг раскладки рядом с курсором. Доступно не во всех приложениях.",
            "settings.launchAtLogin": "Запускать при входе",
            "settings.layout1": "Раскладка 1:",
            "settings.layout2": "Раскладка 2:",
            "settings.autoDetect": "Автоопределение",
            "settings.version": "Лёгкая альтернатива PuntoSwitcher",
            "settings.hotkey": "Тап клавиши-триггера — конвертирует последнее слово. Двойной тап — обратно.",
            "settings.language": "Язык интерфейса:",
            "settings.languageAuto": "Системный",
            "settings.perAppLayout": "Запоминать раскладку для каждого приложения",

        ],

        // ========== DEUTSCH ==========
        "de": [
            "menu.autoSwitch": "RuSwitcher aktivieren",
            "menu.checkPermissions": "Berechtigungen prüfen…",
            "menu.settings": "Einstellungen…",
            "menu.quit": "Beenden",
            "wizard.accessibility.title": "Schritt 1 von 2: Bedienungshilfen",
            "wizard.accessibility.text": "RuSwitcher benötigt die Berechtigung für Bedienungshilfen.\n\nDie Einstellungen werden geöffnet — fügen Sie RuSwitcher hinzu.",
            "wizard.inputMonitoring.title": "Schritt 2 von 2: Eingabeüberwachung",
            "wizard.inputMonitoring.text": "Jetzt wird die Berechtigung für Eingabeüberwachung benötigt.\n\n⚠️ macOS erfordert einen Neustart der App.",
            "wizard.openSettings": "Einstellungen öffnen",
            "wizard.later": "Später",
            "wizard.launchAtLogin.title": "Beim Anmelden starten",
            "wizard.launchAtLogin.text": "Möchten Sie RuSwitcher beim Anmelden automatisch starten?\n\nDies können Sie später in den Einstellungen ändern.",
            "wizard.yes": "Ja",
            "wizard.no": "Nein",
            "settings.title": "RuSwitcher — Einstellungen",
            "settings.tab.general": "Allgemein",
            "settings.tab.about": "Über",
            "settings.autoSwitch": "RuSwitcher aktivieren",
            "settings.trigger": "Auslöser:",
            "settings.triggerRightOnly": "Nur rechte Taste",
            "settings.triggerDoubleTap": "Doppeltipp",
            "settings.triggerHint": "Tippen Sie die gewählte Taste allein, ohne andere Tasten.",
            "menu.keySound": "Layout-Ton (Beta)",
            "menu.caretFlag": "Flagge am Cursor (Beta)",
            "menu.monoIcon": "Monochromes Symbol",
            "settings.caretFlag": "Layout-Flagge am Textcursor anzeigen (Beta)",
            "settings.caretFlag.hint": "Zeigt nach dem Wechsel kurz die Layout-Flagge neben dem Textcursor. Nicht in allen Apps verfügbar.",
            "settings.launchAtLogin": "Beim Anmelden starten",
            "settings.layout1": "Layout 1:",
            "settings.layout2": "Layout 2:",
            "settings.autoDetect": "Automatisch",
            "settings.version": "Leichte Alternative zu PuntoSwitcher",
            "settings.hotkey": "Auslösertaste allein tippen — wandelt das letzte Wort um. Doppeltipp — zurück.",
            "settings.language": "Sprache der Oberfläche:",
            "settings.languageAuto": "Systemstandard",
            "settings.perAppLayout": "Layout pro Anwendung merken",
            "wizard.permissionsReset.title": "Berechtigungen nach Update zurückgesetzt",
            "wizard.permissionsReset.text": "macOS hat die Berechtigungen nach dem App-Update zurückgesetzt.\n\nRuSwitcher entfernt alte Einträge und fordert Berechtigungen erneut an.\nSie müssen nur die Schalter umlegen.",
            "wizard.permissionsOk.title": "Alle Berechtigungen erteilt",
            "wizard.permissionsOk.text": "Bedienungshilfen und Eingabeüberwachung sind aktiviert. RuSwitcher funktioniert.",
        ],

        // ========== FRANÇAIS ==========
        "fr": [
            "menu.autoSwitch": "Activer RuSwitcher",
            "menu.checkPermissions": "Vérifier les autorisations…",
            "menu.settings": "Préférences…",
            "menu.quit": "Quitter",
            "wizard.accessibility.title": "Étape 1 sur 2 : Accessibilité",
            "wizard.accessibility.text": "RuSwitcher a besoin de l'autorisation Accessibilité.\n\nLes réglages vont s'ouvrir — ajoutez RuSwitcher.",
            "wizard.inputMonitoring.title": "Étape 2 sur 2 : Surveillance de l'entrée",
            "wizard.inputMonitoring.text": "L'autorisation de surveillance de l'entrée est maintenant nécessaire.\n\n⚠️ macOS demandera un redémarrage de l'app.",
            "wizard.openSettings": "Ouvrir les réglages",
            "wizard.later": "Plus tard",
            "wizard.launchAtLogin.title": "Lancer au démarrage",
            "wizard.launchAtLogin.text": "Voulez-vous que RuSwitcher démarre automatiquement à l'ouverture de session ?\n\nVous pourrez modifier ce réglage plus tard dans les Préférences.",
            "wizard.yes": "Oui",
            "wizard.no": "Non",
            "settings.title": "RuSwitcher — Préférences",
            "settings.tab.general": "Général",
            "settings.tab.about": "À propos",
            "settings.autoSwitch": "Activer RuSwitcher",
            "settings.trigger": "Déclencheur :",
            "settings.triggerRightOnly": "Touche droite uniquement",
            "settings.triggerDoubleTap": "Double appui",
            "settings.triggerHint": "Appuyez seul sur la touche choisie, sans autre touche.",
            "menu.keySound": "Son de disposition (bêta)",
            "menu.caretFlag": "Drapeau au curseur (bêta)",
            "menu.monoIcon": "Icône monochrome",
            "settings.caretFlag": "Afficher le drapeau de disposition au curseur (bêta)",
            "settings.caretFlag.hint": "Affiche brièvement le drapeau de disposition près du curseur après un changement. Pas disponible dans toutes les apps.",
            "settings.launchAtLogin": "Lancer au démarrage",
            "settings.layout1": "Disposition 1 :",
            "settings.layout2": "Disposition 2 :",
            "settings.autoDetect": "Détection auto",
            "settings.version": "Alternative légère à PuntoSwitcher",
            "settings.hotkey": "Appuyez seul sur la touche déclencheur — convertit le dernier mot. Double appui — inverse.",
            "settings.language": "Langue de l'interface :",
            "settings.languageAuto": "Système par défaut",
            "settings.perAppLayout": "Mémoriser la disposition par application",
            "wizard.permissionsReset.title": "Autorisations réinitialisées après mise à jour",
            "wizard.permissionsReset.text": "macOS a réinitialisé les autorisations suite à la mise à jour.\n\nRuSwitcher supprimera les anciennes entrées et redemandera les autorisations.\nVous n'avez qu'à activer les boutons.",
            "wizard.permissionsOk.title": "Toutes les autorisations sont accordées",
            "wizard.permissionsOk.text": "L’Accessibilité et la Surveillance de la saisie sont activées. RuSwitcher fonctionne.",
        ],

        // ========== ESPAÑOL ==========
        "es": [
            "menu.autoSwitch": "Activar RuSwitcher",
            "menu.checkPermissions": "Verificar permisos…",
            "menu.settings": "Ajustes…",
            "menu.quit": "Salir",
            "wizard.accessibility.title": "Paso 1 de 2: Accesibilidad",
            "wizard.accessibility.text": "RuSwitcher necesita permiso de Accesibilidad.\n\nSe abrirán los ajustes — añada RuSwitcher.",
            "wizard.inputMonitoring.title": "Paso 2 de 2: Monitoreo de entrada",
            "wizard.inputMonitoring.text": "Ahora se necesita el permiso de monitoreo de entrada.\n\n⚠️ macOS requerirá reiniciar la app.",
            "wizard.openSettings": "Abrir ajustes",
            "wizard.later": "Más tarde",
            "wizard.launchAtLogin.title": "Iniciar al arrancar",
            "wizard.launchAtLogin.text": "¿Desea que RuSwitcher se inicie automáticamente al iniciar sesión?\n\nPuede cambiar esto más tarde en Ajustes.",
            "wizard.yes": "Sí",
            "wizard.no": "No",
            "settings.title": "RuSwitcher — Ajustes",
            "settings.tab.general": "General",
            "settings.tab.about": "Acerca de",
            "settings.autoSwitch": "Activar RuSwitcher",
            "settings.trigger": "Disparador:",
            "settings.triggerRightOnly": "Solo tecla derecha",
            "settings.triggerDoubleTap": "Doble toque",
            "settings.triggerHint": "Pulsa sola la tecla elegida, sin otras teclas.",
            "menu.keySound": "Sonido de distribución (beta)",
            "menu.caretFlag": "Bandera en el cursor (beta)",
            "menu.monoIcon": "Icono monocromo",
            "settings.caretFlag": "Mostrar la bandera de distribución en el cursor (beta)",
            "settings.caretFlag.hint": "Muestra brevemente la bandera de distribución junto al cursor tras un cambio. No disponible en todas las apps.",
            "settings.launchAtLogin": "Iniciar al arrancar",
            "settings.layout1": "Disposición 1:",
            "settings.layout2": "Disposición 2:",
            "settings.autoDetect": "Detección automática",
            "settings.version": "Alternativa ligera a PuntoSwitcher",
            "settings.hotkey": "Pulsa sola la tecla disparador — convierte la última palabra. Doble toque — revertir.",
            "settings.language": "Idioma de la interfaz:",
            "settings.languageAuto": "Predeterminado del sistema",
            "settings.perAppLayout": "Recordar disposición por aplicación",
            "wizard.permissionsReset.title": "Permisos restablecidos tras actualización",
            "wizard.permissionsReset.text": "macOS ha restablecido los permisos tras la actualización.\n\nRuSwitcher eliminará las entradas antiguas y solicitará permisos de nuevo.\nSolo necesita activar los interruptores.",
            "wizard.permissionsOk.title": "Todos los permisos concedidos",
            "wizard.permissionsOk.text": "Accesibilidad y Monitorización de entrada están activados. RuSwitcher funciona.",
        ],

        // ========== PORTUGUÊS ==========
        "pt": [
            "menu.autoSwitch": "Ativar RuSwitcher",
            "menu.checkPermissions": "Verificar permissões…",
            "menu.settings": "Configurações…",
            "menu.quit": "Sair",
            "wizard.openSettings": "Abrir configurações",
            "wizard.later": "Mais tarde",
            "settings.title": "RuSwitcher — Configurações",
            "settings.tab.general": "Geral",
            "settings.tab.about": "Sobre",
            "settings.autoSwitch": "Ativar RuSwitcher",
            "settings.trigger": "Gatilho:",
            "settings.triggerRightOnly": "Apenas tecla direita",
            "settings.triggerDoubleTap": "Toque duplo",
            "settings.triggerHint": "Toque sozinho na tecla escolhida, sem outras teclas.",
            "menu.keySound": "Som de layout (beta)",
            "menu.caretFlag": "Bandeira no cursor (beta)",
            "menu.monoIcon": "Ícone monocromático",
            "settings.caretFlag": "Mostrar a bandeira de layout no cursor (beta)",
            "settings.caretFlag.hint": "Mostra brevemente a bandeira de layout ao lado do cursor após a troca. Não disponível em todos os apps.",
            "settings.launchAtLogin": "Iniciar no login",
            "settings.autoDetect": "Detecção automática",
            "settings.language": "Idioma da interface:",
            "settings.languageAuto": "Padrão do sistema",
            "settings.perAppLayout": "Lembrar layout por aplicativo",
            "wizard.permissionsReset.title": "Permissões redefinidas após atualização",
            "wizard.permissionsReset.text": "O macOS redefiniu as permissões porque o app foi atualizado.\n\nO RuSwitcher removerá as entradas antigas e solicitará as permissões novamente.\nVocê só precisa ativar os botões.",
            "wizard.permissionsOk.title": "Todas as permissões concedidas",
            "wizard.permissionsOk.text": "Acessibilidade e Monitoramento de entrada estão ativados. O RuSwitcher está funcionando.",
            "wizard.accessibility.title": "Passo 1 de 2: Acessibilidade",
            "wizard.accessibility.text": "O RuSwitcher precisa da permissão de Acessibilidade.\n\nOs Ajustes serão abertos — adicione o RuSwitcher.\nO app detectará automaticamente.",
            "wizard.inputMonitoring.title": "Passo 2 de 2: Monitoramento de entrada",
            "wizard.inputMonitoring.text": "Agora é necessária a permissão de Monitoramento de entrada.\n\n⚠️ O macOS exigirá reiniciar o app após adicionar.\nO RuSwitcher reiniciará automaticamente.",
            "wizard.launchAtLogin.title": "Abrir ao iniciar sessão",
            "wizard.launchAtLogin.text": "Deseja que o RuSwitcher inicie automaticamente quando você fizer login?\n\nVocê pode alterar isso depois nos Ajustes.",
            "wizard.yes": "Sim",
            "wizard.no": "Não",
            "settings.layout1": "Layout 1:",
            "settings.layout2": "Layout 2:",
            "settings.version": "Alternativa leve ao PuntoSwitcher",
            "settings.hotkey": "Toque sozinho na tecla de gatilho — converte a última palavra. Toque duplo — reverter.",
        ],

        // ========== 中文 ==========
        "zh": [
            "menu.autoSwitch": "启用 RuSwitcher",
            "menu.checkPermissions": "检查权限…",
            "menu.settings": "设置…",
            "menu.quit": "退出",
            "wizard.openSettings": "打开设置",
            "wizard.later": "稍后",
            "settings.title": "RuSwitcher — 设置",
            "settings.tab.general": "通用",
            "settings.tab.about": "关于",
            "settings.autoSwitch": "启用 RuSwitcher",
            "settings.trigger": "触发键：",
            "settings.triggerRightOnly": "仅右侧按键",
            "settings.triggerDoubleTap": "双击",
            "settings.triggerHint": "单独点按所选按键，不要同时按其他键。",
            "menu.keySound": "布局提示音（测试版）",
            "menu.caretFlag": "光标处显示旗标（测试版）",
            "menu.monoIcon": "单色图标",
            "settings.caretFlag": "在文本光标处显示布局旗标（测试版）",
            "settings.caretFlag.hint": "切换后在文本光标旁短暂显示布局旗标。并非所有应用都支持。",
            "settings.launchAtLogin": "登录时启动",
            "settings.autoDetect": "自动检测",
            "settings.language": "界面语言：",
            "settings.languageAuto": "跟随系统",
            "settings.perAppLayout": "按应用记住布局",
            "wizard.permissionsReset.title": "更新后权限已重置",
            "wizard.permissionsReset.text": "由于 App 已更新，macOS 重置了权限。\n\nRuSwitcher 将移除旧条目并重新请求权限。\n你只需重新打开开关即可。",
            "wizard.permissionsOk.title": "已授予所有权限",
            "wizard.permissionsOk.text": "辅助功能和输入监控已启用。RuSwitcher 正常运行。",
            "wizard.accessibility.title": "第 1 步（共 2 步）：辅助功能",
            "wizard.accessibility.text": "RuSwitcher 需要辅助功能权限。\n\n系统设置将打开 — 请添加 RuSwitcher。\nApp 会自动检测。",
            "wizard.inputMonitoring.title": "第 2 步（共 2 步）：输入监控",
            "wizard.inputMonitoring.text": "现在需要输入监控权限。\n\n⚠️ 添加后 macOS 需要重新启动 App。\nRuSwitcher 将自动重启。",
            "wizard.launchAtLogin.title": "登录时启动",
            "wizard.launchAtLogin.text": "是否让 RuSwitcher 在你登录时自动启动？\n\n你可以稍后在设置中更改。",
            "wizard.yes": "是",
            "wizard.no": "否",
            "settings.layout1": "布局 1：",
            "settings.layout2": "布局 2：",
            "settings.version": "PuntoSwitcher 的轻量替代品",
            "settings.hotkey": "单独点按触发键 — 转换最后一个词。双击 — 撤销转换。",
        ],

        // ========== 日本語 ==========
        "ja": [
            "menu.autoSwitch": "RuSwitcher を有効にする",
            "menu.checkPermissions": "権限を確認…",
            "menu.settings": "設定…",
            "menu.quit": "終了",
            "wizard.openSettings": "設定を開く",
            "wizard.later": "後で",
            "settings.title": "RuSwitcher — 設定",
            "settings.tab.general": "一般",
            "settings.tab.about": "このアプリについて",
            "settings.autoSwitch": "RuSwitcher を有効にする",
            "settings.trigger": "トリガー：",
            "settings.triggerRightOnly": "右キーのみ",
            "settings.triggerDoubleTap": "ダブルタップ",
            "settings.triggerHint": "選んだキーを単独で押してください（他のキーと同時押ししない）。",
            "menu.keySound": "レイアウト音（ベータ）",
            "menu.caretFlag": "カーソルに旗（ベータ）",
            "menu.monoIcon": "モノクロアイコン",
            "settings.caretFlag": "テキストカーソルにレイアウトの旗を表示（ベータ）",
            "settings.caretFlag.hint": "切り替え後、テキストカーソルの隣にレイアウトの旗を短く表示します。すべてのアプリで利用できるわけではありません。",
            "settings.launchAtLogin": "ログイン時に起動",
            "settings.autoDetect": "自動検出",
            "settings.language": "インターフェース言語：",
            "settings.languageAuto": "システムデフォルト",
            "settings.perAppLayout": "アプリごとにレイアウトを記憶",
            "wizard.permissionsReset.title": "アップデート後に権限がリセットされました",
            "wizard.permissionsReset.text": "Appがアップデートされたため、macOSが権限をリセットしました。\n\nRuSwitcherは古いエントリを削除し、権限を再度リクエストします。\nスイッチを入れ直すだけです。",
            "wizard.permissionsOk.title": "すべての権限が許可されています",
            "wizard.permissionsOk.text": "アクセシビリティと入力監視が有効です。RuSwitcherは動作しています。",
            "wizard.accessibility.title": "ステップ 1/2：アクセシビリティ",
            "wizard.accessibility.text": "RuSwitcherにはアクセシビリティ権限が必要です。\n\n設定が開きます — RuSwitcherを追加してください。\nAppが自動的に検出します。",
            "wizard.inputMonitoring.title": "ステップ 2/2：入力監視",
            "wizard.inputMonitoring.text": "次に入力監視の権限が必要です。\n\n⚠️ 追加後、macOSはAppの再起動を求めます。\nRuSwitcherは自動的に再起動します。",
            "wizard.launchAtLogin.title": "ログイン時に起動",
            "wizard.launchAtLogin.text": "ログイン時にRuSwitcherを自動的に起動しますか？\n\n後で設定で変更できます。",
            "wizard.yes": "はい",
            "wizard.no": "いいえ",
            "settings.layout1": "レイアウト 1：",
            "settings.layout2": "レイアウト 2：",
            "settings.version": "PuntoSwitcherの軽量な代替",
            "settings.hotkey": "トリガーキーを単独で押す — 直前の単語を変換。ダブルタップ — 元に戻す。",
        ],

        // ========== 한국어 ==========
        "ko": [
            "menu.autoSwitch": "RuSwitcher 사용",
            "menu.checkPermissions": "권한 확인…",
            "menu.settings": "설정…",
            "menu.quit": "종료",
            "wizard.openSettings": "설정 열기",
            "wizard.later": "나중에",
            "settings.title": "RuSwitcher — 설정",
            "settings.tab.general": "일반",
            "settings.tab.about": "정보",
            "settings.autoSwitch": "RuSwitcher 사용",
            "settings.trigger": "트리거:",
            "settings.triggerRightOnly": "오른쪽 키만",
            "settings.triggerDoubleTap": "두 번 탭",
            "settings.triggerHint": "선택한 키를 다른 키 없이 단독으로 누르세요.",
            "menu.keySound": "레이아웃 소리(베타)",
            "menu.caretFlag": "커서에 깃발(베타)",
            "menu.monoIcon": "단색 아이콘",
            "settings.caretFlag": "텍스트 커서에 레이아웃 깃발 표시(베타)",
            "settings.caretFlag.hint": "전환 후 텍스트 커서 옆에 레이아웃 깃발을 잠시 표시합니다. 모든 앱에서 지원되지는 않습니다.",
            "settings.launchAtLogin": "로그인 시 실행",
            "settings.autoDetect": "자동 감지",
            "settings.language": "인터페이스 언어:",
            "settings.languageAuto": "시스템 기본값",
            "settings.perAppLayout": "앱별 레이아웃 기억",
            "wizard.permissionsReset.title": "업데이트 후 권한이 재설정됨",
            "wizard.permissionsReset.text": "앱이 업데이트되어 macOS가 권한을 재설정했습니다.\n\nRuSwitcher가 이전 항목을 제거하고 권한을 다시 요청합니다.\n스위치만 다시 켜면 됩니다.",
            "wizard.permissionsOk.title": "모든 권한이 허용됨",
            "wizard.permissionsOk.text": "손쉬운 사용과 입력 모니터링이 활성화되었습니다. RuSwitcher가 작동 중입니다.",
            "wizard.accessibility.title": "2단계 중 1단계: 손쉬운 사용",
            "wizard.accessibility.text": "RuSwitcher에는 손쉬운 사용 권한이 필요합니다.\n\n설정이 열립니다 — RuSwitcher를 추가하세요.\n앱이 자동으로 감지합니다.",
            "wizard.inputMonitoring.title": "2단계 중 2단계: 입력 모니터링",
            "wizard.inputMonitoring.text": "이제 입력 모니터링 권한이 필요합니다.\n\n⚠️ 추가 후 macOS가 앱 재시작을 요구합니다.\nRuSwitcher가 자동으로 재시작됩니다.",
            "wizard.launchAtLogin.title": "로그인 시 실행",
            "wizard.launchAtLogin.text": "로그인할 때 RuSwitcher를 자동으로 실행할까요?\n\n나중에 설정에서 변경할 수 있습니다.",
            "wizard.yes": "예",
            "wizard.no": "아니요",
            "settings.layout1": "레이아웃 1:",
            "settings.layout2": "레이아웃 2:",
            "settings.version": "PuntoSwitcher의 가벼운 대안",
            "settings.hotkey": "트리거 키를 단독으로 탭 — 마지막 단어를 변환. 두 번 탭 — 되돌리기.",
        ],

        // ========== УКРАЇНСЬКА ==========
        "uk": [
            "menu.autoSwitch": "Увімкнути RuSwitcher",
            "menu.checkPermissions": "Перевірити дозволи…",
            "menu.settings": "Налаштування…",
            "menu.quit": "Вихід",

            "wizard.permissionsReset.title": "Дозволи скинуті після оновлення",
            "wizard.permissionsReset.text": "macOS скинув дозволи через оновлення програми.\n\nRuSwitcher видалить старі записи і запросить дозволи знову.\nВам потрібно лише увімкнути перемикачі.",
            "wizard.accessibility.title": "Крок 1 з 2: Доступність",
            "wizard.accessibility.text": "RuSwitcher потребує дозвіл Accessibility.\n\nВідкриються налаштування — додайте RuSwitcher.\nПрограма визначить автоматично.",
            "wizard.inputMonitoring.title": "Крок 2 з 2: Моніторинг введення",
            "wizard.inputMonitoring.text": "Тепер потрібен дозвіл Input Monitoring.\n\n⚠️ macOS вимагатиме перезапуск програми.\nRuSwitcher перезапуститься автоматично.",
            "wizard.openSettings": "Відкрити налаштування",
            "wizard.later": "Пізніше",
            "wizard.launchAtLogin.title": "Автозавантаження",
            "wizard.launchAtLogin.text": "Запускати RuSwitcher автоматично при вході в систему?\n\nЦе можна змінити пізніше в Налаштуваннях.",
            "wizard.yes": "Так",
            "wizard.no": "Ні",

            "settings.title": "RuSwitcher — Налаштування",
            "settings.tab.general": "Загальні",
            "settings.tab.about": "Про програму",
            "settings.autoSwitch": "Увімкнути RuSwitcher",
            "settings.trigger": "Тригер:",
            "settings.triggerRightOnly": "Лише права клавіша",
            "settings.triggerDoubleTap": "Подвійний тап",
            "settings.triggerHint": "Натискайте вибрану клавішу окремо, без інших клавіш.",
            "menu.keySound": "Звук розкладки (бета)",
            "menu.caretFlag": "Прапор біля курсора (бета)",
            "menu.monoIcon": "Монохромна іконка",
            "settings.caretFlag": "Показувати прапор розкладки біля курсора (бета)",
            "settings.caretFlag.hint": "Після перемикання ненадовго показує прапор розкладки поруч із курсором. Доступно не в усіх програмах.",
            "settings.launchAtLogin": "Запускати при вході",
            "settings.layout1": "Розкладка 1:",
            "settings.layout2": "Розкладка 2:",
            "settings.autoDetect": "Автовизначення",
            "settings.version": "Легка альтернатива PuntoSwitcher",
            "settings.hotkey": "Тап клавіші-тригера — конвертує останнє слово. Подвійний тап — назад.",
            "settings.language": "Мова інтерфейсу:",
            "settings.languageAuto": "Системна",
            "settings.perAppLayout": "Запам'ятовувати розкладку для кожного застосунку",

            "wizard.permissionsOk.title": "Усі дозволи надано",
            "wizard.permissionsOk.text": "«Доступність» та «Моніторинг вводу» увімкнено. RuSwitcher працює.",
        ],

        // ========== БЕЛАРУСКАЯ ==========
        "be": [
            "menu.autoSwitch": "Уключыць RuSwitcher",
            "menu.checkPermissions": "Праверыць дазволы…",
            "menu.settings": "Налады…",
            "menu.quit": "Выхад",

            "wizard.permissionsReset.title": "Дазволы скінуты пасля абнаўлення",
            "wizard.permissionsReset.text": "macOS скінуў дазволы з-за абнаўлення праграмы.\n\nRuSwitcher выдаліць старыя запісы і запытае дазволы нанова.\nВам трэба толькі ўключыць пераключальнікі.",
            "wizard.accessibility.title": "Крок 1 з 2: Даступнасць",
            "wizard.accessibility.text": "RuSwitcher патрабуе дазвол Accessibility.\n\nАдкрыюцца налады — дадайце RuSwitcher.\nПраграма вызначыць аўтаматычна.",
            "wizard.inputMonitoring.title": "Крок 2 з 2: Маніторынг уводу",
            "wizard.inputMonitoring.text": "Цяпер патрэбен дазвол Input Monitoring.\n\n⚠️ macOS запатрабуе перазапуск праграмы.\nRuSwitcher перазапусціцца аўтаматычна.",
            "wizard.openSettings": "Адкрыць налады",
            "wizard.later": "Пазней",
            "wizard.launchAtLogin.title": "Аўтазагрузка",
            "wizard.launchAtLogin.text": "Запускаць RuSwitcher аўтаматычна пры ўваходзе ў сістэму?\n\nГэта можна змяніць пазней у Наладах.",
            "wizard.yes": "Так",
            "wizard.no": "Не",

            "settings.title": "RuSwitcher — Налады",
            "settings.tab.general": "Агульныя",
            "settings.tab.about": "Пра праграму",
            "settings.autoSwitch": "Уключыць RuSwitcher",
            "settings.trigger": "Трыгер:",
            "settings.triggerRightOnly": "Толькі правая клавіша",
            "settings.triggerDoubleTap": "Падвойны тап",
            "settings.triggerHint": "Націскайце выбраную клавішу асобна, без іншых клавіш.",
            "menu.keySound": "Гук раскладкі (бета)",
            "menu.caretFlag": "Сцяг ля курсора (бета)",
            "menu.monoIcon": "Манахромная іконка",
            "settings.caretFlag": "Паказваць сцяг раскладкі ля курсора (бета)",
            "settings.caretFlag.hint": "Пасля пераключэння ненадоўга паказвае сцяг раскладкі побач з курсорам. Даступна не ва ўсіх праграмах.",
            "settings.launchAtLogin": "Запускаць пры ўваходзе",
            "settings.layout1": "Раскладка 1:",
            "settings.layout2": "Раскладка 2:",
            "settings.autoDetect": "Аўтавызначэнне",
            "settings.version": "Лёгкая альтэрнатыва PuntoSwitcher",
            "settings.hotkey": "Тап клавішы-трыгера — канвертуе апошняе слова. Падвойны тап — назад.",
            "settings.language": "Мова інтэрфейсу:",
            "settings.languageAuto": "Сістэмная",
            "settings.perAppLayout": "Запамінаць раскладку для кожнай праграмы",

            "wizard.permissionsOk.title": "Усе дазволы дадзены",
            "wizard.permissionsOk.text": "«Спецыяльныя магчымасці» і «Маніторынг уводу» уключаны. RuSwitcher працуе.",
        ],

        // ========== POLSKI ==========
        "pl": [
            "menu.autoSwitch": "Włącz RuSwitcher",
            "menu.checkPermissions": "Sprawdź uprawnienia…",
            "menu.settings": "Ustawienia…",
            "menu.quit": "Zakończ",
            "wizard.openSettings": "Otwórz ustawienia",
            "wizard.later": "Później",
            "settings.title": "RuSwitcher — Ustawienia",
            "settings.tab.general": "Ogólne",
            "settings.tab.about": "O programie",
            "settings.autoSwitch": "Włącz RuSwitcher",
            "settings.trigger": "Wyzwalacz:",
            "settings.triggerRightOnly": "Tylko prawy klawisz",
            "settings.triggerDoubleTap": "Podwójne naciśnięcie",
            "settings.triggerHint": "Naciśnij wybrany klawisz samodzielnie, bez innych klawiszy.",
            "menu.keySound": "Dźwięk układu (beta)",
            "menu.caretFlag": "Flaga przy kursorze (beta)",
            "menu.monoIcon": "Ikona monochromatyczna",
            "settings.caretFlag": "Pokaż flagę układu przy kursorze (beta)",
            "settings.caretFlag.hint": "Po przełączeniu na chwilę pokazuje flagę układu obok kursora. Niedostępne we wszystkich aplikacjach.",
            "settings.launchAtLogin": "Uruchom przy logowaniu",
            "settings.autoDetect": "Automatyczne wykrywanie",
            "settings.language": "Język interfejsu:",
            "settings.languageAuto": "Domyślny systemowy",
            "settings.perAppLayout": "Zapamiętaj układ dla każdej aplikacji",
            "wizard.permissionsReset.title": "Uprawnienia zresetowane po aktualizacji",
            "wizard.permissionsReset.text": "macOS zresetował uprawnienia, ponieważ aplikacja została zaktualizowana.\n\nRuSwitcher usunie stare wpisy i ponownie poprosi o uprawnienia.\nWystarczy przełączyć przełączniki.",
            "wizard.permissionsOk.title": "Wszystkie uprawnienia przyznane",
            "wizard.permissionsOk.text": "Dostępność i Monitorowanie wejścia są włączone. RuSwitcher działa.",
            "wizard.accessibility.title": "Krok 1 z 2: Dostępność",
            "wizard.accessibility.text": "RuSwitcher potrzebuje uprawnienia Dostępności.\n\nOtworzą się Ustawienia — dodaj RuSwitcher.\nAplikacja wykryje to automatycznie.",
            "wizard.inputMonitoring.title": "Krok 2 z 2: Monitorowanie wejścia",
            "wizard.inputMonitoring.text": "Teraz potrzebne jest uprawnienie Monitorowania wejścia.\n\n⚠️ Po dodaniu macOS będzie wymagać ponownego uruchomienia aplikacji.\nRuSwitcher uruchomi się ponownie automatycznie.",
            "wizard.launchAtLogin.title": "Uruchamiaj przy logowaniu",
            "wizard.launchAtLogin.text": "Czy chcesz, aby RuSwitcher uruchamiał się automatycznie przy logowaniu?\n\nMożesz to zmienić później w Ustawieniach.",
            "wizard.yes": "Tak",
            "wizard.no": "Nie",
            "settings.layout1": "Układ 1:",
            "settings.layout2": "Układ 2:",
            "settings.version": "Lekka alternatywa dla PuntoSwitchera",
            "settings.hotkey": "Naciśnij sam klawisz wyzwalacza — konwertuje ostatnie słowo. Podwójne naciśnięcie — cofnij.",
        ],
        "el": [
            "menu.autoSwitch": "Ενεργοποίηση RuSwitcher",
            "menu.checkPermissions": "Έλεγχος δικαιωμάτων…",
            "menu.settings": "Ρυθμίσεις…",
            "menu.quit": "Έξοδος",
            "wizard.permissionsReset.title": "Τα δικαιώματα επαναφέρθηκαν μετά την ενημέρωση",
            "wizard.permissionsReset.text": "Το macOS επανέφερε τα δικαιώματα επειδή η εφαρμογή ενημερώθηκε.\n\nΤο RuSwitcher θα αφαιρέσει τις παλιές καταχωρήσεις και θα ζητήσει ξανά δικαιώματα.\nΑρκεί να ενεργοποιήσετε τους διακόπτες.",
            "wizard.permissionsOk.title": "Όλα τα δικαιώματα χορηγήθηκαν",
            "wizard.permissionsOk.text": "Η Προσβασιμότητα και η Παρακολούθηση εισόδου είναι ενεργές. Το RuSwitcher λειτουργεί.",
            "wizard.accessibility.title": "Βήμα 1 από 2: Προσβασιμότητα",
            "wizard.accessibility.text": "Το RuSwitcher χρειάζεται δικαίωμα Προσβασιμότητας.\n\nΘα ανοίξουν οι Ρυθμίσεις — προσθέστε το RuSwitcher.\nΗ εφαρμογή θα το εντοπίσει αυτόματα.",
            "wizard.inputMonitoring.title": "Βήμα 2 από 2: Παρακολούθηση εισόδου",
            "wizard.inputMonitoring.text": "Τώρα χρειάζεται δικαίωμα Παρακολούθησης εισόδου.\n\n⚠️ Το macOS θα απαιτήσει επανεκκίνηση της εφαρμογής μετά την προσθήκη.\nΤο RuSwitcher θα επανεκκινήσει αυτόματα.",
            "wizard.openSettings": "Άνοιγμα Ρυθμίσεων",
            "wizard.later": "Αργότερα",
            "wizard.launchAtLogin.title": "Εκκίνηση κατά τη σύνδεση",
            "wizard.launchAtLogin.text": "Θέλετε το RuSwitcher να ξεκινά αυτόματα κατά τη σύνδεσή σας;\n\nΜπορείτε να το αλλάξετε αργότερα στις Ρυθμίσεις.",
            "wizard.yes": "Ναι",
            "wizard.no": "Όχι",
            "settings.title": "RuSwitcher — Ρυθμίσεις",
            "settings.tab.general": "Γενικά",
            "settings.tab.about": "Σχετικά",
            "settings.autoSwitch": "Ενεργοποίηση RuSwitcher",
            "settings.trigger": "Ενεργοποίηση:",
            "settings.triggerRightOnly": "Μόνο δεξί πλήκτρο",
            "settings.triggerDoubleTap": "Διπλό πάτημα",
            "settings.triggerHint": "Πατήστε μόνο του το επιλεγμένο πλήκτρο, χωρίς άλλα πλήκτρα.",
            "menu.keySound": "Ήχος διάταξης (beta)",
            "menu.caretFlag": "Σημαία στον δρομέα (beta)",
            "menu.monoIcon": "Μονόχρωμο εικονίδιο",
            "settings.caretFlag": "Εμφάνιση σημαίας διάταξης στον δρομέα (beta)",
            "settings.caretFlag.hint": "Εμφανίζει σύντομα τη σημαία διάταξης δίπλα στον δρομέα μετά την αλλαγή. Δεν είναι διαθέσιμο σε όλες τις εφαρμογές.",
            "settings.launchAtLogin": "Εκκίνηση κατά τη σύνδεση",
            "settings.layout1": "Διάταξη 1:",
            "settings.layout2": "Διάταξη 2:",
            "settings.autoDetect": "Αυτόματος εντοπισμός",
            "settings.version": "Ελαφριά εναλλακτική του PuntoSwitcher",
            "settings.hotkey": "Πατήστε μόνο το πλήκτρο ενεργοποίησης — μετατρέπει την τελευταία λέξη. Διπλό πάτημα — αναίρεση.",
            "settings.language": "Γλώσσα διεπαφής:",
            "settings.languageAuto": "Προεπιλογή συστήματος",
            "settings.perAppLayout": "Απομνημόνευση διάταξης ανά εφαρμογή",
        ],
        "bg": [
            "menu.autoSwitch": "Включи RuSwitcher",
            "menu.checkPermissions": "Проверка на разрешения…",
            "menu.settings": "Настройки…",
            "menu.quit": "Изход",
            "wizard.permissionsReset.title": "Разрешенията са нулирани след актуализация",
            "wizard.permissionsReset.text": "macOS нулира разрешенията, защото приложението беше актуализирано.\n\nRuSwitcher ще премахне старите записи и ще поиска разрешения отново.\nТрябва само да включите превключвателите.",
            "wizard.permissionsOk.title": "Всички разрешения са дадени",
            "wizard.permissionsOk.text": "Достъпността и Наблюдението на въвеждането са включени. RuSwitcher работи.",
            "wizard.accessibility.title": "Стъпка 1 от 2: Достъпност",
            "wizard.accessibility.text": "RuSwitcher се нуждае от разрешение за Достъпност.\n\nЩе се отворят Настройките — добавете RuSwitcher.\nПриложението ще го открие автоматично.",
            "wizard.inputMonitoring.title": "Стъпка 2 от 2: Наблюдение на въвеждането",
            "wizard.inputMonitoring.text": "Сега е необходимо разрешение за Наблюдение на въвеждането.\n\n⚠️ macOS ще изиска рестартиране на приложението след добавянето.\nRuSwitcher ще се рестартира автоматично.",
            "wizard.openSettings": "Отваряне на настройките",
            "wizard.later": "По-късно",
            "wizard.launchAtLogin.title": "Стартиране при вход",
            "wizard.launchAtLogin.text": "Искате ли RuSwitcher да се стартира автоматично при влизане?\n\nМожете да промените това по-късно в Настройките.",
            "wizard.yes": "Да",
            "wizard.no": "Не",
            "settings.title": "RuSwitcher — Настройки",
            "settings.tab.general": "Общи",
            "settings.tab.about": "Относно",
            "settings.autoSwitch": "Включи RuSwitcher",
            "settings.trigger": "Спусък:",
            "settings.triggerRightOnly": "Само десният клавиш",
            "settings.triggerDoubleTap": "Двойно натискане",
            "settings.triggerHint": "Натиснете избрания клавиш самостоятелно, без други клавиши.",
            "menu.keySound": "Звук на подредбата (бета)",
            "menu.caretFlag": "Флаг при курсора (бета)",
            "menu.monoIcon": "Монохромна икона",
            "settings.caretFlag": "Показвай флага на подредбата при курсора (бета)",
            "settings.caretFlag.hint": "След превключване за кратко показва флага на подредбата до курсора. Не е налично във всички приложения.",
            "settings.launchAtLogin": "Стартиране при вход",
            "settings.layout1": "Подредба 1:",
            "settings.layout2": "Подредба 2:",
            "settings.autoDetect": "Автоматично откриване",
            "settings.version": "Лека алтернатива на PuntoSwitcher",
            "settings.hotkey": "Натиснете самостоятелно клавиша-спусък — преобразува последната дума. Двойно натискане — обратно.",
            "settings.language": "Език на интерфейса:",
            "settings.languageAuto": "Системен по подразбиране",
            "settings.perAppLayout": "Запомняне на подредбата за всяко приложение",
        ],
        "hy": [
            "menu.autoSwitch": "Միացնել RuSwitcher",
            "menu.checkPermissions": "Ստուգել թույլտվությունները…",
            "menu.settings": "Կարգավորումներ…",
            "menu.quit": "Ելք",
            "wizard.permissionsReset.title": "Թույլտվությունները զրոյացվել են թարմացումից հետո",
            "wizard.permissionsReset.text": "macOS-ը զրոյացրել է թույլտվությունները, քանի որ ծրագիրը թարմացվել է.\n\nRuSwitcher-ը կհեռացնի հին գրառումները և կրկին կպահանջի թույլտվություններ.\nՊարզապես միացրեք անջատիչները.",
            "wizard.permissionsOk.title": "Բոլոր թույլտվությունները տրված են",
            "wizard.permissionsOk.text": "Մատչելիությունը և Ներմուծման հսկողությունը միացված են: RuSwitcher-ն աշխատում է.",
            "wizard.accessibility.title": "Քայլ 1/2. Մատչելիություն",
            "wizard.accessibility.text": "RuSwitcher-ին անհրաժեշտ է Մատչելիության թույլտվություն.\n\nԿբացվեն Կարգավորումները — ավելացրեք RuSwitcher.\nԾրագիրն ինքնաշխատ կհայտնաբերի այն.",
            "wizard.inputMonitoring.title": "Քայլ 2/2. Ներմուծման հսկողություն",
            "wizard.inputMonitoring.text": "Այժմ անհրաժեշտ է Ներմուծման հսկողության թույլտվություն.\n\n⚠️ Ավելացնելուց հետո macOS-ը կպահանջի վերագործարկել ծրագիրը.\nRuSwitcher-ն ինքնաշխատ կվերագործարկվի.",
            "wizard.openSettings": "Բացել Կարգավորումները",
            "wizard.later": "Ավելի ուշ",
            "wizard.launchAtLogin.title": "Գործարկել մուտքի ժամանակ",
            "wizard.launchAtLogin.text": "Ցանկանո՞ւմ եք, որ RuSwitcher-ն ինքնաշխատ գործարկվի մուտք գործելիս:\n\nԴա կարող եք փոխել ավելի ուշ Կարգավորումներում.",
            "wizard.yes": "Այո",
            "wizard.no": "Ոչ",
            "settings.title": "RuSwitcher — Կարգավորումներ",
            "settings.tab.general": "Հիմնական",
            "settings.tab.about": "Մասին",
            "settings.autoSwitch": "Միացնել RuSwitcher",
            "settings.trigger": "Գործարկիչ:",
            "settings.triggerRightOnly": "Միայն աջ ստեղնը",
            "settings.triggerDoubleTap": "Կրկնակի հպում",
            "settings.triggerHint": "Հպեք ընտրված ստեղնն առանձին, առանց այլ ստեղների.",
            "menu.keySound": "Դասավորության ձայն (բետա)",
            "menu.caretFlag": "Դրոշ կուրսորի մոտ (բետա)",
            "menu.monoIcon": "Միագույն պատկերակ",
            "settings.caretFlag": "Ցուցադրել դասավորության դրոշը կուրսորի մոտ (բետա)",
            "settings.caretFlag.hint": "Փոխարկումից հետո կարճ ժամանակով ցույց է տալիս դասավորության դրոշը կուրսորի կողքին։ Հասանելի չէ բոլոր հավելվածներում։",
            "settings.launchAtLogin": "Գործարկել մուտքի ժամանակ",
            "settings.layout1": "Դասավորություն 1:",
            "settings.layout2": "Դասավորություն 2:",
            "settings.autoDetect": "Ինքնահայտնաբերում",
            "settings.version": "PuntoSwitcher-ի թեթև այլընտրանք",
            "settings.hotkey": "Հպեք գործարկիչ ստեղնն առանձին — փոխարկում է վերջին բառը: Կրկնակի հպում — հետ.",
            "settings.language": "Միջերեսի լեզու:",
            "settings.languageAuto": "Համակարգի լռելյայն",
            "settings.perAppLayout": "Հիշել դասավորությունն ըստ ծրագրի",
        ],
        "ka": [
            "menu.autoSwitch": "RuSwitcher-ის ჩართვა",
            "menu.checkPermissions": "ნებართვების შემოწმება…",
            "menu.settings": "პარამეტრები…",
            "menu.quit": "გასვლა",
            "wizard.permissionsReset.title": "ნებართვები განულდა განახლების შემდეგ",
            "wizard.permissionsReset.text": "macOS-მა განულა ნებართვები, რადგან აპი განახლდა.\n\nRuSwitcher წაშლის ძველ ჩანაწერებს და თავიდან მოითხოვს ნებართვებს.\nუბრალოდ ჩართეთ გადამრთველები.",
            "wizard.permissionsOk.title": "ყველა ნებართვა მინიჭებულია",
            "wizard.permissionsOk.text": "წვდომადობა და შეყვანის მონიტორინგი ჩართულია. RuSwitcher მუშაობს.",
            "wizard.accessibility.title": "ნაბიჯი 1/2: წვდომადობა",
            "wizard.accessibility.text": "RuSwitcher-ს სჭირდება წვდომადობის ნებართვა.\n\nგაიხსნება პარამეტრები — დაამატეთ RuSwitcher.\nაპი ავტომატურად აღმოაჩენს მას.",
            "wizard.inputMonitoring.title": "ნაბიჯი 2/2: შეყვანის მონიტორინგი",
            "wizard.inputMonitoring.text": "ახლა საჭიროა შეყვანის მონიტორინგის ნებართვა.\n\n⚠️ დამატების შემდეგ macOS მოითხოვს აპის გადატვირთვას.\nRuSwitcher ავტომატურად გადაიტვირთება.",
            "wizard.openSettings": "პარამეტრების გახსნა",
            "wizard.later": "მოგვიანებით",
            "wizard.launchAtLogin.title": "გაშვება შესვლისას",
            "wizard.launchAtLogin.text": "გსურთ RuSwitcher ავტომატურად გაეშვას სისტემაში შესვლისას?\n\nამის შეცვლა მოგვიანებით შეგიძლიათ პარამეტრებში.",
            "wizard.yes": "დიახ",
            "wizard.no": "არა",
            "settings.title": "RuSwitcher — პარამეტრები",
            "settings.tab.general": "ზოგადი",
            "settings.tab.about": "შესახებ",
            "settings.autoSwitch": "RuSwitcher-ის ჩართვა",
            "settings.trigger": "ტრიგერი:",
            "settings.triggerRightOnly": "მხოლოდ მარჯვენა ღილაკი",
            "settings.triggerDoubleTap": "ორმაგი შეხება",
            "settings.triggerHint": "დააჭირეთ არჩეულ ღილაკს ცალკე, სხვა ღილაკების გარეშე.",
            "menu.keySound": "განლაგების ხმა (ბეტა)",
            "menu.caretFlag": "დროშა კურსორთან (ბეტა)",
            "menu.monoIcon": "მონოქრომული ხატულა",
            "settings.caretFlag": "განლაგების დროშის ჩვენება ტექსტის კურსორთან (ბეტა)",
            "settings.caretFlag.hint": "გადართვის შემდეგ მოკლედ აჩვენებს განლაგების დროშას კურსორის გვერდით. ხელმისაწვდომია არა ყველა აპში.",
            "settings.launchAtLogin": "გაშვება შესვლისას",
            "settings.layout1": "განლაგება 1:",
            "settings.layout2": "განლაგება 2:",
            "settings.autoDetect": "ავტომატური აღმოჩენა",
            "settings.version": "PuntoSwitcher-ის მსუბუქი ალტერნატივა",
            "settings.hotkey": "დააჭირეთ ტრიგერ ღილაკს ცალკე — გარდაქმნის ბოლო სიტყვას. ორმაგი შეხება — უკან.",
            "settings.language": "ინტერფეისის ენა:",
            "settings.languageAuto": "სისტემის ნაგულისხმევი",
            "settings.perAppLayout": "განლაგების დამახსოვრება თითო აპზე",
        ],
    ]
}
